### PR TITLE
[TASK] Use GitHub error formatting for phpstan CI

### PR DESCRIPTION
**Pull request by lukaszuznanski**
Resolves: #493

### CODE REVIEW

**Comment by oliverklee** [comment]
I have tested this [in a PR](https://github.com/TYPO3-Documentation/tea/pull/666) and would expect to be able to see something there. Am I missing something?

**Comment by lukaszuznanski** [comment]
Output should be different. I will provide separate pr with bug that phpstan should catch and we will compare them.

**Comment by oliverklee** [comment]
> Using this new command shows new output in CLI, which I believe is for github actions, but in github actions I can't see any difference. Maybe I'm missing something here?

I honestly have no idea. Maybe we need to do some more research on this.

**Comment by lukaszuznanski** [comment]
@oliverklee I think it's enabled by default now, take a look here:
https://github.com/FriendsOfTYPO3/tea/pull/889/files
it looks like it's enabled, I think we can close this PR

**Comment by oliverklee** [comment]
How can I see whether it's enabled?

**Comment by lukaszuznanski** [comment]
It was visible in this PR when phpstan failed, it's not anymore :/

**Comment by lukaszuznanski** [comment]
Closing for now, will reopen with clean branch

**Pull request closed without merging**
