### PR TITLE
[FEATURE] Add Composer scripts and a CI job for Rector

### LINKED ISSUE #851: Add Rector
## Goal
As a developer I want to add Rector.
## Acceptance Criteria

- [x] add TYPO3 Rector as a dependency
- [x] add a Rector configuration file and keep it out of releases
- [x] add a Composer script to run Rector to change stuff
- [x] add a Composer script to run Rector to analyze stuff (`--dry-run`) 
- [x] add the Rector script to `ci:static` 
- [x] add the dry-run Rector script to the fix Composer command
- [x] add Rector check to CI

## Additional Information
We probably can steal from this project: https://github.com/simonschaufi/gkh_rss_import/

### PR DESCRIPTION
**Pull request by oliverklee**
Closes #851

### CODE REVIEW

**Review by lukaszuznanski — APPROVED** [review]

**Review by lukaszuznanski — CHANGES_REQUESTED** [review]
There is gitlab CI job missing there

**Comment by oliverklee** [comment]
I've added the GitLab CI job now.

**Comment by oliverklee** [comment]
https://git.typo3.org/qa/example-extension/-/pipelines/66062

**Comment by oliverklee** [comment]
https://git.typo3.org/qa/example-extension/-/pipelines/66062

**Comment by oliverklee** [comment]
> There is gitlab CI job missing there

@lukaszuznanski  Which one?

Was it missing before? Or did I remove it in this change? (If it was missing before, I'd like to tackle that in a separate change.)

**Comment by oliverklee** [comment]
@DanielSiepmann @lukaszuznanski gentle ping for a review :-)

**Review by DanielSiepmann — APPROVED** [review]

**Comment by DanielSiepmann** [comment]
@oliverklee can you solve the conflicts introduced with merge of https://github.com/FriendsOfTYPO3/tea/pull/1464 ?

**Comment by oliverklee** [comment]
Rebased and repushed.

**Comment by DanielSiepmann** [comment]
@oliverklee I can't merge. I guess @lukaszuznanski needs to review again to "remove" the requested change?

**Review by lukaszuznanski — APPROVED** [review]

**Pull request merged**
