### PR TITLE
[TASK] Use PHP 8.3 by default in `runTests.sh`

### PR DESCRIPTION
**Pull request by oliverklee**
Let's use the most performant available PHP version for local development.

### CODE REVIEW

**Review by sbuerk — APPROVED** [review]
Personally I prefere to use the minimum version locally to ensure early (locally) not to use syntax only available in higher versions.
Performance in runTests.sh for tests and tools should be negitable.

On the otherhand, it's a question of preference and technically absolutly fine to use PHP8.3 as both cores support them and all related tools.

**Review by lukaszuznanski — APPROVED** [review]
I can confirm that it's working on local env.

**Comment by DanielSiepmann** [comment]
If this is about performance: Should we do the same for all other versions, e.g. database as well?
mysql for some reason is the only dbms where the highest version is the default.

I'd prefer to streamline the highest / lowest version throughout all the usages. TYPO3 has highest value by default. Or should that be a different issue?

**Comment by oliverklee** [comment]
> I'd prefer to streamline the highest / lowest version throughout all the usages. TYPO3 has highest value by default. Or should that be a different issue?

Let's do that for the DBMS versions in a separate issue. (And I'm all for using the highest possible version for the supported TYPO3 versions by default.)

**Pull request merged**
