### PR TITLE
Fix for functional tests on gitlab CI

### PR DESCRIPTION
**Pull request by lukaszuznanski**
Resolves: #976 

This is related to different settings in error reporting.
https://git.typo3.org/qa/example-extension/-/commit/ccc186123268e8fc0af2cb3d6447d9eed8bc3394

### CODE REVIEW

**Comment by oliverklee** [comment]
Can't we set the INI values via `Tests/Functional/FunctionalTests.xml` instead?

**Comment by lukaszuznanski** [comment]
> Can't we set the INI values via `Tests/Functional/FunctionalTests.xml` instead?

This sounds like much better solution. I will.

**Comment by lukaszuznanski** [comment]
It looks like it doesn't work properly when it's set in phpunit.xml, maybe it's too late to set this?

**Comment by oliverklee** [comment]
Okay, then let's keep the change as is.

**Review by oliverklee — APPROVED** [review]

**Pull request merged**
